/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import controlador.Administrador;
import controlador.Dependencia;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import GUI.Resources.*;
import TDA.Lista;
import controlador.Expediente;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;
/**
 *
 * @author andre
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            InputStream is = getClass().getResourceAsStream("/fonts/OpenSans-Bold.ttf");
            Font openSansBold = Font.createFont(Font.TRUETYPE_FONT, is).deriveFont(Font.PLAIN, 24f);
            InputStream is2 = getClass().getResourceAsStream("/fonts/OpenSans-Bold.ttf");
            Font openSansBold2 = Font.createFont(Font.TRUETYPE_FONT, is2).deriveFont(Font.PLAIN, 15f);
            InputStream is3 = getClass().getResourceAsStream("/fonts/OpenSans-VariableFont_wdth,wght.ttf");
            Font openSans = Font.createFont(Font.TRUETYPE_FONT, is3).deriveFont(Font.PLAIN, 10f);
            setLayout(null);
            bg.setLayout(null);
            iniciosesion.setFont(openSansBold);
            alertaUsuario.setFont(openSans);
            alertaContraseña.setFont(openSans);  
            
            // Texto Usuario
            usuario.setFont(openSans);
            nombreUsuario.setFont(openSans);
            nombreUsuario.setBorder(new RoundedBorder(8,Color.BLACK));
            usuario.setOpaque(true);
            usuario.setBackground(Color.WHITE); // Mismo fondo que el JTextField
            // Texto Contraseña
            contraseña.setFont(openSans);
            nombreContraseña.setFont(openSans);
            nombreContraseña.setBorder(new RoundedBorder(8,Color.BLACK));
            contraseña.setOpaque(true);
            contraseña.setBackground(Color.WHITE); // Mismo fondo que el JTextField
            // Boton Ingresar
            ingresar.setFont(openSansBold2);
            ingresar.setContentAreaFilled(false);
            ingresar.setFocusPainted(false);
            ingresar.setBorderPainted(false);
            ingresar.setOpaque(false);
                    
            ingresar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
                @Override
                public void paint(Graphics g, JComponent c) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                    g2.setColor(c.getBackground());
                    g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 10, 10);
                    g2.dispose();
                    super.paint(g, c);
                } 
            });
            

        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        contraseña = new javax.swing.JLabel();
        iniciosesion = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        usuario = new javax.swing.JLabel();
        alertaUsuario = new javax.swing.JLabel();
        usuarioIcon = new javax.swing.JLabel();
        alertaContraseña = new javax.swing.JLabel();
        contraseñaIcon = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombreContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contraseña.setText("Contraseña");
        bg.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 56, -1));

        iniciosesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        iniciosesion.setText("Inicio de Sesión");
        bg.add(iniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 190, 30));

        ingresar.setBackground(new java.awt.Color(239, 111, 35));
        ingresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("Iniciar Sesión");
        ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarMouseExited(evt);
            }
        });
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        bg.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 335, 220, 40));

        usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuario.setText("Usuario");
        bg.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 195, 39, -1));

        alertaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        alertaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        alertaUsuario.setText("Usuario Incorrecto.");
        bg.add(alertaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 246, 164, -1));

        usuarioIcon.setBackground(new java.awt.Color(255, 255, 255));
        usuarioIcon.setForeground(new java.awt.Color(255, 255, 255));
        usuarioIcon.setText("🛈");
        bg.add(usuarioIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 246, -1, -1));

        alertaContraseña.setBackground(new java.awt.Color(255, 255, 255));
        alertaContraseña.setForeground(new java.awt.Color(255, 255, 255));
        alertaContraseña.setText("Contraseña incorrecta.");
        bg.add(alertaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 311, 164, -1));

        contraseñaIcon.setBackground(new java.awt.Color(255, 255, 255));
        contraseñaIcon.setForeground(new java.awt.Color(255, 255, 255));
        contraseñaIcon.setText("🛈");
        bg.add(contraseñaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 311, -1, -1));

        nombreUsuario.setSelectionColor(new java.awt.Color(239, 123, 54));
        nombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreUsuarioFocusLost(evt);
            }
        });
        bg.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 205, 220, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        fondo.setText("jLabel2");
        bg.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 390, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 29));

        nombreContraseña.setSelectionColor(new java.awt.Color(239, 123, 54));
        nombreContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreContraseñaFocusLost(evt);
            }
        });
        nombreContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreContraseñaActionPerformed(evt);
            }
        });
        bg.add(nombreContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 270, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
        
        if (nombreUsuario.getText().equals("20232157") && nombreContraseña.getText().equals("1234")) {
        
        Administrador.setInstancia(nombreUsuario.getText(), nombreContraseña.getText());
        
        String[] nombresDeps = {
            "Mesa de Partes", "Decanato", "Tesorería",
            "Biblioteca", "Bienestar Universitario", "Secretaría Académica"
        };

        Lista<Dependencia> deps = new Lista<>();
        
        
            for (String nombresDep : nombresDeps) {
                Dependencia d = new Dependencia(nombresDep);
                deps.agregar(d);
            }
            
        Dependencia.setInstancias(deps);
        // Abrir la pantalla de menú principal
        Registro menu = new Registro();
        menu.setVisible(true);

        // Cerrar login
        dispose();  
        
            
        }else {
            if(!nombreUsuario.getText().equals("20232157")){
                alertaUsuario.setForeground(new Color(239,111,35));
                usuarioIcon.setForeground(new Color(239,111,35));
            }else{
                alertaUsuario.setForeground(Color.WHITE);
                usuarioIcon.setForeground(Color.WHITE);
            }
            if(!nombreContraseña.getText().equals("1234")){
                alertaContraseña.setForeground(new Color(239,111,35));
                contraseñaIcon.setForeground(new Color(239,111,35));
            }else{
                alertaContraseña.setForeground(Color.WHITE);
                contraseñaIcon.setForeground(Color.WHITE);
            }
        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void nombreContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreContraseñaActionPerformed

    private void nombreUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreUsuarioFocusGained
        nombreUsuario.setBorder(new RoundedBorder(10,new Color(239,111,35)));
        usuario.setForeground(new Color(239,111,35));
    }//GEN-LAST:event_nombreUsuarioFocusGained

    private void nombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreUsuarioFocusLost
        nombreUsuario.setBorder(new RoundedBorder(10,Color.BLACK));
        usuario.setForeground(Color.BLACK);
    }//GEN-LAST:event_nombreUsuarioFocusLost

    private void nombreContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreContraseñaFocusGained
        nombreContraseña.setBorder(new RoundedBorder(10,new Color(239,111,35)));
        contraseña.setForeground(new Color(239,111,35));
    }//GEN-LAST:event_nombreContraseñaFocusGained

    private void nombreContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreContraseñaFocusLost
        nombreContraseña.setBorder(new RoundedBorder(10,Color.BLACK));
        contraseña.setForeground(Color.BLACK);
    }//GEN-LAST:event_nombreContraseñaFocusLost

    private void ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseEntered
        Color colorHover = ingresar.getBackground().darker();
        ingresar.setBackground(colorHover);
    }//GEN-LAST:event_ingresarMouseEntered

    private void ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseExited
        Color colorNormal = new Color(239, 111, 35);
        ingresar.setBackground(colorNormal);
    }//GEN-LAST:event_ingresarMouseExited
        
            
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertaContraseña;
    private javax.swing.JLabel alertaUsuario;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel contraseñaIcon;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel iniciosesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField nombreContraseña;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuarioIcon;
    // End of variables declaration//GEN-END:variables
}
